---
title: "Análises Descritivas"
author: "LucianoRogerio; Caroline Cardoso"
date: "2021-10-25"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---

## Introduction

```{r}
suppressMessages(library(tidyverse)); suppressMessages(library(here)); suppressMessages(library(reshape2))
#### Boxplot de colecoes nucleares

## Colecoes nucleares estimadas com dados Fenotipicos

Method1 <- read.table(here::here("output", "DadosCCPheno1.CSV"), header = T,
                      sep = ";", dec = ".",
                      colClasses = c(rep("factor", times = 36),
                                    rep("numeric", times = 16)))
Method1$HCNMod <- as.factor(Method1$HCNMod)
Method1$DMCsg <- as.numeric(as.character(Method1$DMCsg))


Method2 <- read.table(here::here("output", "DadosCCPheno2.CSV"), header = T,
                      sep = ";", dec = ".",
                      colClasses = c(rep("factor", times = 36),
                                     rep("numeric", times = 16)))
Method2$HCNMod <- as.factor(Method2$HCNMod)
Method2$DMCsg <- as.numeric(as.character(Method2$DMCsg))
colnames(Method2)[1] <- "Acessos"


Method3 <- read.table(here::here("output", "DadosCCPheno3.CSV"), header = T,
                      sep = ";", dec = ".",
                      colClasses = c(rep("factor", times = 36),
                                     rep("numeric", times = 16)))
Method3$HCNMod <- as.factor(Method3$HCNMod)
Method3$DMCsg <- as.numeric(as.character(Method3$DMCsg))

## Colecoes Nucleares estimadas com dados Moleculares

Method4 <- read.table(here::here("output", "DadosCCGeno1.CSV"), header = T, 
                      sep = ";", dec = ".",
                      colClasses = c(rep("factor", times = 36),
                                    rep("numeric", times = 16)))
Method4$HCNMod <- as.factor(Method4$HCNMod)
Method4$DMCsg <- as.numeric(as.character(Method4$DMCsg))


Method5 <- read.table(here::here("output", "DadosCCGeno2.CSV"), header = T, 
                      sep = ";", dec = ".",
                      colClasses = c(rep("factor", times = 36),
                                     rep("numeric", times = 16)))
Method5$HCNMod <- as.factor(Method5$HCNMod)
Method5$DMCsg <- as.numeric(as.character(Method5$DMCsg))


Method6 <- read.table(here::here("output", "DadosCCGeno3.CSV"), header = T, 
                      sep = ";", dec = ".",
                      colClasses = c(rep("factor", times = 36),
                                     rep("numeric", times = 16)))
Method6$HCNMod <- as.factor(Method6$HCNMod)
Method6$DMCsg <- as.numeric(as.character(Method6$DMCsg))

Method7 <- read.table(here::here("output", "DadosCCGeno4.CSV"), header = T,
                      sep = ";", dec = ".",
                      colClasses = c(rep("factor", times = 36),
                                    rep("numeric", times = 16)))
Method7$HCNMod <- as.factor(Method7$HCNMod)
Method7$DMCsg <- as.numeric(as.character(Method7$DMCsg))


Method8 <- read.table(here::here("output", "DadosCCGeno5.CSV"), header = T,
                      sep = ";", dec = ".",
                      colClasses = c(rep("factor", times = 36),
                                     rep("numeric", times = 16)))
Method8$HCNMod <- as.factor(Method8$HCNMod)
Method8$DMCsg <- as.numeric(as.character(Method8$DMCsg))


Method9 <- read.table(here::here("output", "DadosCCGeno6.CSV"), header = T,
                      sep = ";", dec = ".",
                      colClasses = c(rep("factor", times = 36),
                                     rep("numeric", times = 16)))
Method9$HCNMod <- as.factor(Method9$HCNMod)
Method9$DMCsg <- as.numeric(as.character(Method9$DMCsg))

Method10 <- read.table(here::here("output", "DadosCCGeno7.CSV"), header = T,
                       sep = ";", dec = ".",
                       colClasses = c(rep("factor", times = 36),
                                    rep("numeric", times = 16)))
Method10$HCNMod <- as.factor(Method10$HCNMod)
Method10$DMCsg <- as.numeric(as.character(Method10$DMCsg))


Method11 <- read.table(here::here("output", "DadosCCGeno8.CSV"), header = T,
                       sep = ";", dec = ".",
                      colClasses = c(rep("factor", times = 36),
                                     rep("numeric", times = 16)))
Method11$HCNMod <- as.factor(Method11$HCNMod)
Method11$DMCsg <- as.numeric(as.character(Method11$DMCsg))


Method12 <- read.table(here::here("output", "DadosCCGeno9.CSV"), header = T,
                       sep = ";", dec = ".",
                       colClasses = c(rep("factor", times = 36),
                                     rep("numeric", times = 16)))
Method12$HCNMod <- as.factor(Method12$HCNMod)
Method12$DMCsg <- as.numeric(as.character(Method12$DMCsg))

## Dados Fenotipicos do Banco de Germoplasma de Mandioca da EMBRAPA Mandioca

AllBAG <- read.table(here::here("data", "DadosSelCaroline.CSV"), header = T,
                     sep = ",", dec = ".",
                     colClasses = c(rep("factor", times = 36),
                                    rep("numeric", times = 16)))
AllBAG$HCNMod <- as.factor(AllBAG$HCNMod)
AllBAG$DMCsg <- as.numeric(as.character(AllBAG$DMCsg))


AllBAG$Data <- rep("BAG", times = nrow(AllBAG))
AllBAG$Method <- rep("BAG", times = nrow(AllBAG))

Method1$Data <- rep("Pheno", times = nrow(Method1))
Method1$Method <- rep("GW/CH", times = nrow(Method1))

Method2$Data <- rep("Pheno", times = nrow(Method2))
Method2$Method <- rep("CH", times = nrow(Method2))

Method3$Data <- rep("Pheno", times = nrow(Method3))
Method3$Method <- rep("GW/MLST", times = nrow(Method3))

Method4$Data <- rep("Geno", times = nrow(Method4))
Method4$Method <- rep("MR/SH", times = nrow(Method4))

Method5$Data <- rep("Geno", times = nrow(Method5))
Method5$Method <- rep("CE/SH", times = nrow(Method5))

Method6$Data <- rep("Geno", times = nrow(Method6))
Method6$Method <- rep("MR/EH", times = nrow(Method6))

Method7$Data <- rep("Geno", times = nrow(Method7))
Method7$Method <- rep("CE/EH", times = nrow(Method7))

Method8$Data <- rep("Geno", times = nrow(Method8))
Method8$Method <- rep("MR/AC", times = nrow(Method8))

Method9$Data <- rep("Geno", times = nrow(Method9))
Method9$Method <- rep("CE/AC", times = nrow(Method9))

Method10$Data <- rep("Geno", times = nrow(Method10))
Method10$Method <- rep("AM/MLST", times = nrow(Method10))

Method11$Data <- rep("Geno", times = nrow(Method11))
Method11$Method <- rep("MR/MLST", times = nrow(Method11))

Method12$Data <- rep("Geno", times = nrow(Method12))
Method12$Method <- rep("CE/MLST", times = nrow(Method12))

Alldataset <- rbind(AllBAG, Method1, Method2, Method3,
                    Method4, Method5, Method6,
                    Method7, Method8, Method9,
                    Method10, Method11, Method12)

saveRDS(Alldataset, here::here("output", "AllDataCCCaroline.RDS"))

QualityTrait <- colnames(Alldataset)[2:36]


AlldataSetQuant <- Alldataset %>% select(-QualityTrait)
AlldataSetQuali <- Alldataset %>% select(Acessos, QualityTrait, Data, Method)

AlldataSetQuant2 <- melt(AlldataSetQuant, id.vars = c("Acessos", "Data", "Method"),
       variable.name = "Trait", value.name = "Value")
head(AlldataSetQuant2)


AlldataSetQuant2$Data <- factor(AlldataSetQuant2$Data,
                                levels = c("BAG", "Pheno", "Geno"), ordered = T)
AlldataSetQuant2$Method <- factor(AlldataSetQuant2$Method,
                                levels = c("BAG", "GW/CH", "GW/MLST", "CH",
                                           "MR/SH", "MR/EH", "MR/AC", "MR/MLST",
                                           "CE/SH", "CE/EH", "CE/AC", "CE/MLST",
                                           "AM/MLST"),
                                ordered = T)

## Remover os outliers

filter_lims <- function(x){
  l <- boxplot.stats(x)$stats[1]
  u <- boxplot.stats(x)$stats[5]

  for (i in 1:length(x)){
    x[i] <- ifelse(x[i]>l & x[i]<u, x[i], NA)
  }
  return(x)
}


AlldataSetQuant3 <- AlldataSetQuant2 %>% group_by(Trait, Method) %>%
  mutate(Value2 = filter_lims(Value))


## Plotar o boxplot por conjunto de caracteres
Foliar <- c("RetFoliar", "ComprLobulo", "LargLobulo",
            "RelComprLar", "AltPl", "PPA",
            "ComprPeciolo")
Root <- c("FRY", "EspEntreCasca", "ComprMedRzs",
          "DiamMedRzs", "NRPl", "DMCsg", "IndColh")
Root2 <- c("FRYC", "FRYNC")
```

```{r, fig.align='center', fig.height=9}
### Caracteres morfologicos de parte aerea
AlldataSetQuant3 %>% filter(Trait%in%Foliar) %>%
  ggplot(mapping = aes(y = Value2, fill = Data, x = Method), message = F) +
  geom_boxplot() + facet_wrap(~Trait, scales = "free_y", ncol = 2,) + ylab(NULL) +
  theme(axis.text.x = element_text(angle = 320, hjust = 0.1,
        colour = c("blue", rep("red", 3), rep("green", 9))))

### Caracteres morfologicos de raiz
AlldataSetQuant3 %>% filter(Trait%in%Root) %>%
  ggplot(mapping = aes(y = Value2, fill = Data, x = Method)) +
  geom_boxplot() + facet_wrap(~Trait, scales = "free_y", ncol = 2) + ylab(NULL) +
  theme(axis.text.x = element_text(angle = 320, hjust = 0.1,
        colour = c("blue", rep("red", 3), rep("green", 9))))

```

```{r, fig.align='center', fig.height=3}
AlldataSetQuant3 %>% filter(Trait%in%Root2) %>%
  ggplot(mapping = aes(y = Value2, fill = Data, x = Method)) +
  geom_boxplot() + facet_wrap(~Trait, scales = "free_y", ncol = 2) + ylab(NULL) +
  theme(axis.text.x = element_text(angle = 320, hjust = 0.1,
        colour = c("blue", rep("red", 3), rep("green", 9))))

```

```{r}
AlldataSetQuali2 <- melt(AlldataSetQuali, id.vars = c("Acessos", "Data", "Method"),
       variable.name = "Trait", value.name = "Value")
head(AlldataSetQuali2)

AlldataSetQuali3 <- AlldataSetQuali2 %>% filter (!is.na(Value)) %>%
  group_by(Trait, Data, Method) %>% summarise(N = table(Value, useNA = "no"),
                                              Score = names(N)) 

AlldataSetQuali3$Data <- factor(AlldataSetQuali3$Data,
                                levels = c("BAG", "Pheno", "Geno"), ordered = T)
AlldataSetQuali3$Method <- factor(AlldataSetQuali3$Method,
                                levels = c("BAG", "GW/CH", "GW/MLST", "CH",
                                           "MR/SH", "MR/EH", "MR/AC", "MR/MLST",
                                           "CE/SH", "CE/EH", "CE/AC", "CE/MLST",
                                           "AM/MLST"),
                                ordered = T)
AlldataSetQuali3$Score <- factor(AlldataSetQuali3$Score,
                                 levels = c(0, 1, 2, 3, 4, 5, 6, 7, 8, 9,
                                            30, 40, 45, 50, 60, 70, 80, 85, 90,
                                            95, 100, 105, 110, 115, 120, 130,
                                            140, 150, 160))

traitsFolha <- levels(AlldataSetQuali3$Trait)[c(1:4, 8, 12:17, 20, 23)]
traitsCaule <- levels(AlldataSetQuali3$Trait)[c(5:7, 18:19, 21:22, 28, 32:34)]
traitsRaiz <- levels(AlldataSetQuali3$Trait)[c(9:11, 24:27, 29:31, 35)]

traitsFolha1 <- traitsFolha[c(1:5)]
traitsFolha2 <- traitsFolha[c(6, 8, 10, 13)]
traitsFolha3 <- traitsFolha[c(7, 9, 11:12)]

traitsCaule1 <- traitsCaule[c(1:3, 8:9)]
traitsCaule2 <- traitsCaule[c(4:7, 11)]
traitsCaule3 <- traitsCaule[c(10)]

traitsRaiz1 <- traitsRaiz[c(1:3, 5, 8:9)]
traitsRaiz2 <- traitsRaiz[c(4, 6:7, 10:11)]

# Fig 1. Barplot with the First set of stem traits
AlldataSetQuali3 %>% filter(Trait%in%traitsCaule1) %>% 
  ggplot(aes(y = N, x = Method, fill = Score)) +
  geom_bar(stat = "identity", position = "fill") +
  facet_wrap(~Trait, ncol = 2, scales = "fixed") + ylab(NULL) +
  scale_fill_viridis_d() +
  theme(axis.text.x = element_text(angle = 320, hjust = 0.1,
                                   colour = c("blue", rep("red", 3), rep("green", 9))))

# Fig 2. Barplot with the Second set of stem traits
AlldataSetQuali3 %>% filter(Trait%in%traitsCaule2) %>% 
  ggplot(aes(y = N, x = Method, fill = Score)) +
  geom_bar(stat = "identity", position = "fill") +
  facet_wrap(~Trait, ncol = 2, scales = "fixed") + ylab(NULL) +
  scale_fill_viridis_d() +
  theme(axis.text.x = element_text(angle = 320, hjust = 0.1,
                                   colour = c("blue", rep("red", 3), rep("green", 9))))

# Fig 3. Barplot with the branch angle
AlldataSetQuali3 %>% filter(Trait%in%traitsCaule3) %>% 
  ggplot(aes(y = N, x = Method, fill = Score)) +
  geom_bar(stat = "identity", position = "fill") +
  facet_wrap(~Trait, ncol = 2, scales = "fixed") + ylab(NULL) +
  scale_fill_viridis_d() +
  theme(axis.text.x = element_text(angle = 320, hjust = 0.1,
                                   colour = c("blue", rep("red", 3), rep("green", 9))))

# Fig 4. Barplot with the First set of leaf traits
AlldataSetQuali3 %>% filter(Trait%in%traitsFolha1) %>% 
  ggplot(aes(y = N, x = Method, fill = Score)) +
  geom_bar(stat = "identity", position = "fill") +
  facet_wrap(~Trait, ncol = 2, scales = "fixed") + ylab(NULL) +
  scale_fill_viridis_d() +
  theme(axis.text.x = element_text(angle = 320, hjust = 0.1,
                                   colour = c("blue", rep("red", 3), rep("green", 9))))

# Fig 5. Barplot with the Second set of leaf traits
AlldataSetQuali3 %>% filter(Trait%in%traitsFolha2) %>% 
  ggplot(aes(y = N, x = Method, fill = Score)) +
  geom_bar(stat = "identity", position = "fill") +
  facet_wrap(~Trait, ncol = 2, scales = "fixed") + ylab(NULL) +
  scale_fill_viridis_d() +
  theme(axis.text.x = element_text(angle = 320, hjust = 0.1,
                                   colour = c("blue", rep("red", 3), rep("green", 9))))

# Fig 6. Barplot with the Third set of leaf traits
AlldataSetQuali3 %>% filter(Trait%in%traitsFolha3) %>% 
  ggplot(aes(y = N, x = Method, fill = Score)) +
  geom_bar(stat = "identity", position = "fill") +
  facet_wrap(~Trait, ncol = 2, scales = "fixed") + ylab(NULL) +
  scale_fill_viridis_d() +
  theme(axis.text.x = element_text(angle = 320, hjust = 0.1,
                                   colour = c("blue", rep("red", 3), rep("green", 9))))

# Fig 7. Barplot with the First set of root traits
AlldataSetQuali3 %>% filter(Trait%in%traitsRaiz1) %>% 
  ggplot(aes(y = N, x = Method, fill = Score)) +
  geom_bar(stat = "identity", position = "fill") +
  facet_wrap(~Trait, ncol = 2, scales = "fixed") + ylab(NULL) +
  scale_fill_viridis_d() +
  theme(axis.text.x = element_text(angle = 320, hjust = 0.1,
                                   colour = c("blue", rep("red", 3), rep("green", 9))))

# Fig 8. Barplot with the Second set of root traits
AlldataSetQuali3 %>% filter(Trait%in%traitsRaiz2) %>% 
  ggplot(aes(y = N, x = Method, fill = Score)) +
  geom_bar(stat = "identity", position = "fill") +
  facet_wrap(~Trait, ncol = 2, scales = "fixed") + ylab(NULL) +
  scale_fill_viridis_d() +
  theme(axis.text.x = element_text(angle = 320, hjust = 0.1,
                                   colour = c("blue", rep("red", 3), rep("green", 9))))

```

Back - [Coleções Nucleares Genotípicas](CNGeno.html)
Next - [Estimativas de Diversidade genética](DivGen.html)
[Home](index.html)
