---
title: "Coleções Nucleares Fenotípicas"
author: "LucianoRogerio; Caroline Cardoso"
date: "2021-10-25"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---

## Coleções Nucleares Fenotípicas

```{r lendo dados fenotipicos, eval = FALSE}
suppressMessages(library(tidyverse))
DataCar <- readRDS(file = here::here("output", "DataSelPreparedCar.rds"))
```

### Coleção Nuclear 1 - Distância de Gower e pacote CoreHunter

```{r Estimacacao da Primeira colecao nuclear fen, eval = FALSE}
library(corehunter); library(StatMatch)
DistCar <- gower.dist(data.x = DataCar[,-1],)
row.names(DistCar) <- colnames(DistCar) <- DataCar$Acessos
DistCar2 <- distances(DistCar)

CCSize <- round(nrow(DistCar) * 0.2, digits = 0)

CCC1 <- sampleCore(DistCar2, objective(type = "EN", measure = "PD"), size = CCSize)

DataCarCCPheno1 <- DataCar[DataCar$Acessos%in%CCC1$sel,]

write.table(DataCarCCPheno1, here::here("output", "CCPhenData", "DadosCCPheno1.CSV"),
            quote = F, sep = ";", dec = ".")
```

### Coleção Nuclear 2 - Algoritmo pacote CoreHunter

```{r Estimacacao da Segunda colecao nuclear fen, eval = FALSE}
DataCarP <- phenotypes(data = as.data.frame(DataCar[,-1]))
CCC2 <- sampleCore(DataCarP, objective(type = "EN", measure = "GD"), size = CCSize)

DataCarCCPheno2 <- DataCar[rownames(DataCar)%in%CCC2$sel,]

write.table(DataCarCCPheno2, file = here::here("output", "CCPhenData", "DadosCCPheno2.CSV"),
            quote = F, sep = ";", dec = ".")
```

### Coleção Nuclear 3 - Distância de Gower e Algoritmo MLST DARwin software

```{r Preparando a matriz de distancias de Gower para DARwin, eval = FALSE}
DistCar <- as.dist(DistCar)
cat(nrow(DistCar), "\n", file = here::here("output", "MatrizGowerCaroline.phy"))
write.table(x = as.matrix(DistCar), file = here::here("output", "MatrizGowerCaroline.phy"),
          append = TRUE, quote = FALSE, sep = "\t", col.names = FALSE)

CCSize
```




```{r Obtendo os resultados de DARwin e separando os resultados, eval = FALSE}
SelDARwin <- read.table(here::here("output","MatrizGowerCaroline.DON"),
                             sep = "\t", header = T, skip = 2,
                             nrows = 1628)
table(SelDARwin$Tree.Sample_172)
ClonesSel <- SelDARwin %>% filter(Tree.Sample_172 == "Kept") %>%
  select(Name)
DataCarCCPheno3 <- DataCar[DataCar$Acessos%in%ClonesSel$Name,]

write.table(DataCarCCPheno3, file= here::here("output", "CCPhenData", "DadosCCPheno3.CSV"),
            quote = F, sep = ";", dec = ".")
```

Back - [Dados Moleculares - Seleção](GenoData.html)

Next - [Coleções Nucleares Genotípicas](CNGeno.html)

[Home](index.html)
