---
title: "Coleções Nucleares - 1° Capítulo Caroline"
author: "LucianoRogerio; Caroline Cardoso"
site: workflowr::wflow_site
output:
  workflowr::wflow_html:
    toc: false
editor_options:
  chunk_output_type: console
---

Introdução
==========
O termo coleção nuclear é utilizado para designar um conjunto de acessos, menor do que o número total que compõe um determinado Banco Ativo de Germoplasma (BAG), que representa a máxima diversidade genética potencial, com a menor redundância possível (FRANKEL, 1984).
Devido ao seu tamanho reduzido, a coleção nuclear possibilita o estudo intensivo e a utilização de forma eficiente do germoplasma, formando uma base completa de informações (CORDEIRO, ABADIE, 2007). Ressaltando que as coleções nucleares devem ser menores que a coleção principal, entre as proporções de 5% a 20%, representando até 90% da diversidade de toda coleção (ARAUJO, 2008).

Objetivos
=========  
  O objetivo deste trabalho é criar uma coleção nuclear, que represente a máxima diversidade da coleção completa, eliminando acessos redundantes, e aumentando a acessibilidade e o uso eficiente dos recursos genéticos do banco ativo de germoplasma de mandioca da EMBRAPA.
  
  
Material e métodos
==================
### [Dados Fenotípicos - Seleção](PhenoData.html)

Primeiro iremos realizar uma seleção prévia das características quanto a variabilidade genética

### [Dados Moleculares - Seleção](GenoData.html)

### [Coleções Nucleares Fenotípicas](CCPheno.html)

### [Coleções Nucleares Genotípicas](CCGeno.html)

### [Análises Discriminantes](AnDis.html)

### [Estimativas de Diversidade genética](DivGen.html)



